### ISSUE TITLE
sum(hours) for project row

### ISSUE THREAD

**Issue by genuinefafa** [soluciones3f/loki#12]
"nice to have" sum(hours) for each project row, so we can know how many hours were commited to each project.

**Comment by fniwes** [comment]
With the current interface, you can only see hours for a full fortnight. You will not be able to see hours per week unless we add a readonly column in the middle of the view. I am not sure about the usefulness or how to implement this issue.

**Comment by genuinefafa** [comment]
That suits me. The full fortnight is ok.
